package view;

import java.awt.Window;
import javax.swing.SwingUtilities;

public class MainView extends javax.swing.JFrame {

    private LAFInterface lafManager;
    
    /**
     * Creates new form App
     */
    public MainView(LAFInterface lafManager) {
        this.lafManager = lafManager;
        initComponents();
        updateMenuText();
    }
    
    private void updateUI(){
        for(Window window : getWindows()) {
            SwingUtilities.updateComponentTreeUI(window);
        }
    }
    
    private void updateMenuText(){
        
        jMenuItemThemeChanger.setText("Current Theme: " + lafManager.getLAF().getName());
        
        String mode = lafManager.getCurrentType();
        String togglerMenuText;
        togglerMenuText = switch (mode) {
            case "LIGHT" -> "Light Mode";
            case "DARK" -> "Dark Mode";
            default -> "Untracked UI Theme";
        };
        jMenuItemModeToggler.setText(togglerMenuText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonNewLoan = new javax.swing.JButton();
        jButtonNewReader = new javax.swing.JButton();
        jButtonNewBook = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        jButtonNewLoan1 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();
        jMenuThemes = new javax.swing.JMenu();
        jMenuItemThemeChanger = new javax.swing.JMenuItem();
        jMenuItemModeToggler = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.LINE_AXIS));

        jToolBar1.setFloatable(true);
        jToolBar1.setRollover(true);

        jButtonNewLoan.setText("New Loan");
        jButtonNewLoan.setFocusable(false);
        jButtonNewLoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewLoan.setMaximumSize(new java.awt.Dimension(110, 55));
        jButtonNewLoan.setMinimumSize(new java.awt.Dimension(55, 55));
        jButtonNewLoan.setName(""); // NOI18N
        jButtonNewLoan.setPreferredSize(new java.awt.Dimension(55, 55));
        jButtonNewLoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNewLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewLoanActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonNewLoan);
        jButtonNewLoan.getAccessibleContext().setAccessibleDescription("");

        jButtonNewReader.setText("New Reader");
        jButtonNewReader.setFocusable(false);
        jButtonNewReader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewReader.setMaximumSize(new java.awt.Dimension(110, 55));
        jButtonNewReader.setMinimumSize(new java.awt.Dimension(55, 55));
        jButtonNewReader.setName(""); // NOI18N
        jButtonNewReader.setPreferredSize(new java.awt.Dimension(55, 55));
        jButtonNewReader.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonNewReader);

        jButtonNewBook.setText("New Book");
        jButtonNewBook.setFocusable(false);
        jButtonNewBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewBook.setMaximumSize(new java.awt.Dimension(110, 55));
        jButtonNewBook.setMinimumSize(new java.awt.Dimension(55, 55));
        jButtonNewBook.setName(""); // NOI18N
        jButtonNewBook.setPreferredSize(new java.awt.Dimension(55, 55));
        jButtonNewBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonNewBook);

        topPanel.add(jToolBar1);

        jToolBar4.setFloatable(true);
        jToolBar4.setRollover(true);

        jButtonNewLoan1.setText("AAAAA");
        jButtonNewLoan1.setFocusable(false);
        jButtonNewLoan1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewLoan1.setMaximumSize(new java.awt.Dimension(110, 55));
        jButtonNewLoan1.setMinimumSize(new java.awt.Dimension(55, 55));
        jButtonNewLoan1.setName(""); // NOI18N
        jButtonNewLoan1.setPreferredSize(new java.awt.Dimension(55, 55));
        jButtonNewLoan1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNewLoan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewLoan1ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButtonNewLoan1);

        topPanel.add(jToolBar4);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenuEdit.setText("Edit");

        jMenuThemes.setText("Themes");

        jMenuItemThemeChanger.setText("Current Theme: FlatLaf Example");
        jMenuItemThemeChanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThemeChangerActionPerformed(evt);
            }
        });
        jMenuThemes.add(jMenuItemThemeChanger);

        jMenuItemModeToggler.setText("Example Mode");
        jMenuItemModeToggler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleMode(evt);
            }
        });
        jMenuThemes.add(jMenuItemModeToggler);

        jMenuEdit.add(jMenuThemes);

        jMenuBar2.add(jMenuEdit);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewLoanActionPerformed

    private void jButtonNewLoan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewLoan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewLoan1ActionPerformed

    private void jMenuItemThemeChangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThemeChangerActionPerformed
        lafManager.cycleLAF();
        updateMenuText();
        updateUI();
        jMenuEdit.doClick();
        jMenuThemes.doClick();
    }//GEN-LAST:event_jMenuItemThemeChangerActionPerformed

    private void toggleMode(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleMode
        // TODO add your handling code here:
        lafManager.cycleType();
        lafManager.cycleLAF();
        updateUI();
        updateMenuText();
        jMenuEdit.doClick();
        jMenuThemes.doClick();
    }//GEN-LAST:event_toggleMode

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButtonNewBook;
    private javax.swing.JButton jButtonNewLoan;
    private javax.swing.JButton jButtonNewLoan1;
    private javax.swing.JButton jButtonNewReader;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuItemModeToggler;
    private javax.swing.JMenuItem jMenuItemThemeChanger;
    private javax.swing.JMenu jMenuThemes;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
